### PR TITLE
removed go-messaging-lib dependency

### PR DESCRIPTION
**Pull request by mezzi**

### CODE REVIEW

**Comment by mezzi** [comment]
Note: vendor.yml is just for the `example` package which still uses go-messaging-lib. I couldn't get it to work though.

**Comment by tnguyen-veri** [comment]
Is there a problem we're trying to solve with this?  Copying the interface from go-messaging-lib means in future we must remember to update in 2 places if that interface ever changes.

**Comment by mezzi** [comment]
It decouples the edge-messages library from go-messaging-lib while still maintaining compatibility with its interfaces. Stream Ingestor, Speechmatics (and it's clones), engine-toolkit etc don't use go-messaging-lib but have to pull in all it's dependencies since edge-messages depends on it. This was causing build problems for me last night because some of the dependencies (uber packages) have moved or disappeared.

Note that we are are only depending on certain interface methods like `Payload()` so I can probably pare this down even more. For example, here:

```
func ToOfflineIngestionRequest(e messaging.Event) (OfflineIngestionRequest, error) {
	msg := OfflineIngestionRequest{}
	err := decode(e.Payload(), &msg)
	if err != nil {
		return msg, fmt.Errorf("error decoding to OfflineIngestionRequest: %v", err)
	}
	return msg, nil
} 
```

We expect e to have a method called `Payload` which returns `[]byte`. If this changes in go-messaging-lib, we would have to change it here anyway, so we don't benefit much from sharing the interface type.

I don't even think we need the `KafkaMessage` type that I added, because all we need is something that implements `func Message() interface{}` to be compatible with go-messaging-lib's Produce method. I might be able to get rid of that as well.

By removing this dependency from here, it removed about 25 dependencies from edge-stream-ingestor which I think is a huge win.

**Comment by mezzi** [comment]
ugh, actually this may not work because I just noticed this:

https://github.com/veritone/go-messaging-lib/blob/master/kafka/producer.go#L86-L89
```
func (p *producer) Produce(_ context.Context, msg messaging.Messager, _ ...messaging.Event) error {
	kafkaMsg, ok := msg.Message().(*Message)
	if !ok {
		return fmt.Errorf("unsupported Kafka message: %s", spew.Sprint(msg))
	}
```

This requires the underlying value of the interface{} returned by `Message()` to be of type `*Message`. I don't really understand the point of this, it's very tedious to work with, especially when writing unit tests.

**Comment by mezzi** [comment]
for perspective, the difference of adding go-messaging-lib as a dependency:

https://github.com/veritone/edge-stream-ingestor/pull/55/commits/5a7b857071737538059ac01cac9edce9a25c5645

**Comment by tnguyen-veri** [comment]
Understood the problem/context.  Agreed that this is worthwhile and a small price to pay.

**Comment by tnguyen-veri** [comment]
You mentioned a few enhancements/optimizations you want to try.  Please let me know when you're done and I'll take another look.

**Comment by mezzi** [comment]
Actually I realized this isn't going to work (see my comment about the Produce method above). Maybe we can revise go-messaging-lib at some point and revisit this. I'll close the PR for now.

**Comment by tnguyen-veri** [comment]
> ugh, actually this may not work because I just noticed this:
> 
> https://github.com/veritone/go-messaging-lib/blob/master/kafka/producer.go#L86-L89
> 
> ```
> func (p *producer) Produce(_ context.Context, msg messaging.Messager, _ ...messaging.Event) error {
> 	kafkaMsg, ok := msg.Message().(*Message)
> 	if !ok {
> 		return fmt.Errorf("unsupported Kafka message: %s", spew.Sprint(msg))
> 	}
> ```
> This requires the underlying value of the interface{} returned by `Message()` to be of type `*Message`. I don't really understand the point of this, it's very tedious to work with, especially when writing unit tests.

I think this is due to Sam designed the same interface for both Kafka and NSQ but each implements a different concrete type which requires Message() to return interface{} then cast to correct type.

To solve this we might need to break Kafka and NSQ apart and update interface for each to use a concrete type instead of interface{}.

**Comment by mezzi** [comment]
> To solve this we might need to break Kafka and NSQ apart and update interface for each to use a concrete type instead of interface{}.

agreed

**Pull request closed without merging**
