### PR TITLE
VTN-14959 Add chunk_status_and_output and task_status_and_output messages

### PR DESCRIPTION
**Pull request by tnguyen-veri**
https://steel-ventures.atlassian.net/browse/VTN-14959

### CODE REVIEW

**Comment by tnguyen-veri** [comment]
@ctsiokos-veritone you can start updating OW using these message formats and the logic outlined in https://docs.google.com/document/d/1o8OqzmhyruFASW7E17mVzJw7P23QWW8sKr85LwnOveY/edit

**Comment by ctsiokos-veritone** [comment]
Yes, I'm starting by reviewing this and then moving on to OW.

**Comment by ctsiokos-veritone** [comment]
Was the removal of `ProcessingCount` from the ChunkSummary intentional?

**Comment by tnguyen-veri** [comment]
Mezzi - I was looking for a shorter name too, thanks for the suggestion, I'll use it.

Christos - Yes ProcessingCount was intentionally removed along with Processing status.

**Comment by tnguyen-veri** [comment]
Made following changes:
- Renamed ChunkStatusAndOutput to ChunkResult
- Renamed TaskStatusAndOutput to TaskResult
All unit tests passed

**Pull request merged**
